# Required
mainServers = [
  "94882524378968064",
  "587215460127473703"
]
inboxServer = "255438591214223362"
logChannel = "255438591214223362"

# Common settings
prefix = "!"
anonPrefix = "!!"
status = "DM to contact staff"
responseMessage = "Thank you for your message! Our mod team will reply to you here as soon as possible."
closeMessage = "Thank you for contacting us, the ticket is now closed. If you need more help, feel free to send us another message!"
mentionRoles = ["here"]
alwaysReply = false
alwaysReplyAnon = false
rolesInThreadHeader = true
useNicknames = true
ignoreAccidentalThreads = true
allowMove = true
typingProxyToInbox = true
typingProxyToUser = false
pingOnBotMention = false
overwatchGuildId = "94882524378968064"
banGuildId = "587215460127473703"

[automation]
newThreadCategory = [
  { server = "587215460127473703", category = "587226082814722068" }
]

[requirements]
accountAge = 0.166
accountAgeDeniedMessage = "Your Discord account is not old enough to contact modmail yet"
timeOnServer = 10
timeOnServerDeniedMessage = "You haven't been a member of the server for long enough to contact modmail yet"

[web]
port = "8001"
url = "https://modmail.owdiscord.org"
